apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-streamer-hpa
  namespace: okd-streamer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-streamer
  minReplicas: 3  # 최소 2개 유지
  maxReplicas: 5 # 최대 10개까지 확장
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # CPU 사용량이 50%를 넘어가면 Pod 추가 생성
